#!/bin/bash

set -e

INSTALLDIR=`pwd`/libosmscout/install

git clone https://github.com/rinigus/libosmscout.git || true
(cd libosmscout && git checkout geocoder-nlp)

mkdir -p libosmscout/build || true
(cd libosmscout/build && cmake -DCMAKE_INSTALL_PREFIX:PATH=$INSTALLDIR -DBUILD_WITH_OPENMP=OFF -DOSMSCOUT_BUILD_DOC_API=OFF -DOSMSCOUT_BUILD_BINDING_JAVA=OFF -DOSMSCOUT_BUILD_MAP_OPENGL=OFF  -DOSMSCOUT_BUILD_MAP_AGG=OFF -DOSMSCOUT_BUILD_MAP_CAIRO=OFF -DOSMSCOUT_BUILD_MAP_SVG=OFF -DOSMSCOUT_BUILD_MAP_QT=OFF -DOSMSCOUT_BUILD_MAP_IOSX=OFF -DOSMSCOUT_BUILD_TESTS=OFF -DOSMSCOUT_BUILD_DEMOS=OFF -DOSMSCOUT_BUILD_BINDING_CSHARP=OFF -DOSMSCOUT_BUILD_CLIENT_QT=OFF -DOSMSCOUT_BUILD_TOOL_OSMSCOUT2=OFF -DOSMSCOUT_BUILD_TOOL_STYLEEDITOR=OFF -DGPERFTOOLS_USAGE=OFF -DOSMSCOUT_BUILD_TOOL_IMPORT=ON -DBUILD_IMPORT_TOOL_FOR_DISTRIBUTION=ON -DBUILD_SHARED_LIBS=OFF .. && make -j8 && make install)
