#ifndef GEOCODER_VERSION_H
#define GEOCODER_VERSION_H

#define GEOCODERNLP_MAJOR_VERSION 1
#define GEOCODERNLP_MINOR_VERSION 0
#define GEOCODERNLP_PATCH_VERSION 0

#define GEOCODERNLP_VERSION (GEOCODERNLP_MAJOR_VERSION*100000) + (GEOCODERNLP_MINOR_VERSION*100) + (GEOCODERNLP_PATCH_VERSION)

#define _STRINGIFY(n) _STRINGIFY_HELPER(n)
#define _STRINGIFY_HELPER(n) #n

#define GEOCODERNLP_VERSION_STRING  \
                _STRINGIFY(GEOCODERNLP_MAJOR_VERSION) "." \
                _STRINGIFY(GEOCODERNLP_MINOR_VERSION) "." \
                _STRINGIFY(GEOCODERNLP_PATCH_VERSION)


#endif // GEOCODER_VERSION_H
